# Generated by Django 5.2.6 on 2025-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_file_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_rovoked',
            field=models.BooleanField(default=False),
        ),
    ]
