# Generated by Django 5.2.6 on 2025-09-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_is_rovoked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_rovoked',
            new_name='is_revoked',
        ),
    ]
